### ISSUE TITLE
Song Converter Failing with Error

### ISSUE THREAD

**Issue by nightshining** [blakelivingston/DuinoTune#10]
```

Song: /Users/user_name/Documents/Arduino/libraries/DuinoTune/test_songs/test.xrns changed.
Updated Arduino library at: /Users/user_name/Documents/Arduino/libraries/DuinoTune/output_songs/test/src/test.xrns
Error translating song: too many values to unpack
 Trace: Traceback (most recent call last):
  File "song_converter.py", line 100, in songWatcher
    xrns2tt.xrns_to_tt(songfile, out_path_songname, {})
  File "/Users/user_name/Documents/Arduino/libraries/DuinoTune/song_converter/xrns2tt.py", line 148, in xrns_to_tt
    inst.parse(vol_env, tpl, lpb)
  File "/Users/user_name/Documents/Arduino/libraries/DuinoTune/song_converter/xrns2tt.py", line 71, in parse
    tick, level = point.text.split(',')
ValueError: too many values to unpack
```

**Comment by blakelivingston** [comment]
Hi, thanks for the report!
It's been a long time since I've updated the conversion utility - I'll give it a shot with the latest Renoise version within the next week or so. I'm guessing that their internal format has shifted a bit.

**Comment by nightshining** [comment]
Yea reverting back to Renoise 3.1 was the solution. Thank you.
